/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Lockable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Lockable__factory>;
    getContractFactory(
      name: "Testable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Testable__factory>;
    getContractFactory(
      name: "Timer",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Timer__factory>;
    getContractFactory(
      name: "ExpiringContractInterface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ExpiringContractInterface__factory>;
    getContractFactory(
      name: "FinancialProductLibrary",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FinancialProductLibrary__factory>;
    getContractFactory(
      name: "ExpiringContractInterface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ExpiringContractInterface__factory>;
    getContractFactory(
      name: "LongShortPairFinancialProductLibrary",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LongShortPairFinancialProductLibrary__factory>;
    getContractFactory(
      name: "ExpiringMultiPartyMock",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ExpiringMultiPartyMock__factory>;
    getContractFactory(
      name: "FloatiesLongShortPairFinancialProductLibrary",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FloatiesLongShortPairFinancialProductLibrary__factory>;
    getContractFactory(
      name: "Greeter",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Greeter__factory>;
    getContractFactory(
      name: "ImpermanentLossLongShortPairFinancialProductLibrary",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ImpermanentLossLongShortPairFinancialProductLibrary__factory>;
    getContractFactory(
      name: "LinearLongShortPairFinancialProductLibrary",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LinearLongShortPairFinancialProductLibrary__factory>;
    getContractFactory(
      name: "YamExpiringMultiPartyMock",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.YamExpiringMultiPartyMock__factory>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
  }
}
