/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface LinearLongShortPairFinancialProductLibraryInterface
  extends ethers.utils.Interface {
  functions: {
    "longShortPairParameters(address)": FunctionFragment;
    "percentageLongCollateralAtExpiry(int256)": FunctionFragment;
    "setLongShortPairParameters(address,int256,int256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "longShortPairParameters",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "percentageLongCollateralAtExpiry",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setLongShortPairParameters",
    values: [string, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "longShortPairParameters",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "percentageLongCollateralAtExpiry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setLongShortPairParameters",
    data: BytesLike
  ): Result;

  events: {};
}

export class LinearLongShortPairFinancialProductLibrary extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: LinearLongShortPairFinancialProductLibraryInterface;

  functions: {
    longShortPairParameters(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { upperBound: BigNumber; lowerBound: BigNumber }
    >;

    percentageLongCollateralAtExpiry(
      expiryPrice: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    setLongShortPairParameters(
      longShortPair: string,
      upperBound: BigNumberish,
      lowerBound: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  longShortPairParameters(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & { upperBound: BigNumber; lowerBound: BigNumber }
  >;

  percentageLongCollateralAtExpiry(
    expiryPrice: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  setLongShortPairParameters(
    longShortPair: string,
    upperBound: BigNumberish,
    lowerBound: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    longShortPairParameters(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { upperBound: BigNumber; lowerBound: BigNumber }
    >;

    percentageLongCollateralAtExpiry(
      expiryPrice: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setLongShortPairParameters(
      longShortPair: string,
      upperBound: BigNumberish,
      lowerBound: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    longShortPairParameters(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    percentageLongCollateralAtExpiry(
      expiryPrice: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setLongShortPairParameters(
      longShortPair: string,
      upperBound: BigNumberish,
      lowerBound: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    longShortPairParameters(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    percentageLongCollateralAtExpiry(
      expiryPrice: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setLongShortPairParameters(
      longShortPair: string,
      upperBound: BigNumberish,
      lowerBound: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
