/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface PricelessPositionManagerInterface extends ethers.utils.Interface {
  functions: {
    "_getSyntheticDecimals(address)": FunctionFragment;
    "cancelTransferPosition()": FunctionFragment;
    "cancelWithdrawal()": FunctionFragment;
    "collateralCurrency()": FunctionFragment;
    "contractState()": FunctionFragment;
    "create(tuple,tuple)": FunctionFragment;
    "cumulativeFeeMultiplier()": FunctionFragment;
    "deposit(tuple)": FunctionFragment;
    "depositTo(address,tuple)": FunctionFragment;
    "emergencyShutdown()": FunctionFragment;
    "expirationTimestamp()": FunctionFragment;
    "expire()": FunctionFragment;
    "expiryPrice()": FunctionFragment;
    "financialProductLibrary()": FunctionFragment;
    "finder()": FunctionFragment;
    "getCollateral(address)": FunctionFragment;
    "getCurrentTime()": FunctionFragment;
    "getOutstandingRegularFees(uint256)": FunctionFragment;
    "gulp()": FunctionFragment;
    "minSponsorTokens()": FunctionFragment;
    "payRegularFees()": FunctionFragment;
    "pfc()": FunctionFragment;
    "positions(address)": FunctionFragment;
    "priceIdentifier()": FunctionFragment;
    "rawTotalPositionCollateral()": FunctionFragment;
    "redeem(tuple)": FunctionFragment;
    "remargin()": FunctionFragment;
    "repay(tuple)": FunctionFragment;
    "requestTransferPosition()": FunctionFragment;
    "requestWithdrawal(tuple)": FunctionFragment;
    "setCurrentTime(uint256)": FunctionFragment;
    "settleExpired()": FunctionFragment;
    "timerAddress()": FunctionFragment;
    "tokenCurrency()": FunctionFragment;
    "totalPositionCollateral()": FunctionFragment;
    "totalTokensOutstanding()": FunctionFragment;
    "transferPositionPassedRequest(address)": FunctionFragment;
    "transformPrice(tuple,uint256)": FunctionFragment;
    "transformPriceIdentifier(uint256)": FunctionFragment;
    "withdraw(tuple)": FunctionFragment;
    "withdrawPassedRequest()": FunctionFragment;
    "withdrawalLiveness()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "_getSyntheticDecimals",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelTransferPosition",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cancelWithdrawal",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "collateralCurrency",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "contractState",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "create",
    values: [{ rawValue: BigNumberish }, { rawValue: BigNumberish }]
  ): string;
  encodeFunctionData(
    functionFragment: "cumulativeFeeMultiplier",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [{ rawValue: BigNumberish }]
  ): string;
  encodeFunctionData(
    functionFragment: "depositTo",
    values: [string, { rawValue: BigNumberish }]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyShutdown",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "expirationTimestamp",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "expire", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "expiryPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "financialProductLibrary",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "finder", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getCollateral",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentTime",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getOutstandingRegularFees",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "gulp", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "minSponsorTokens",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "payRegularFees",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "pfc", values?: undefined): string;
  encodeFunctionData(functionFragment: "positions", values: [string]): string;
  encodeFunctionData(
    functionFragment: "priceIdentifier",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rawTotalPositionCollateral",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "redeem",
    values: [{ rawValue: BigNumberish }]
  ): string;
  encodeFunctionData(functionFragment: "remargin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "repay",
    values: [{ rawValue: BigNumberish }]
  ): string;
  encodeFunctionData(
    functionFragment: "requestTransferPosition",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestWithdrawal",
    values: [{ rawValue: BigNumberish }]
  ): string;
  encodeFunctionData(
    functionFragment: "setCurrentTime",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "settleExpired",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "timerAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "tokenCurrency",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalPositionCollateral",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalTokensOutstanding",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferPositionPassedRequest",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "transformPrice",
    values: [{ rawValue: BigNumberish }, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transformPriceIdentifier",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [{ rawValue: BigNumberish }]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawPassedRequest",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawalLiveness",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "_getSyntheticDecimals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelTransferPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelWithdrawal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "collateralCurrency",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "contractState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "create", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cumulativeFeeMultiplier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "depositTo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "emergencyShutdown",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "expirationTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "expire", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "expiryPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "financialProductLibrary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "finder", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCollateral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOutstandingRegularFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "gulp", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "minSponsorTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "payRegularFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pfc", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "positions", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "priceIdentifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rawTotalPositionCollateral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "redeem", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "remargin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "repay", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "requestTransferPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestWithdrawal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCurrentTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settleExpired",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "timerAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenCurrency",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalPositionCollateral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalTokensOutstanding",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferPositionPassedRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transformPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transformPriceIdentifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawPassedRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawalLiveness",
    data: BytesLike
  ): Result;

  events: {
    "ContractExpired(address)": EventFragment;
    "Deposit(address,uint256)": EventFragment;
    "EmergencyShutdown(address,uint256,uint256)": EventFragment;
    "EndedSponsorPosition(address)": EventFragment;
    "FinalFeesPaid(uint256)": EventFragment;
    "NewSponsor(address)": EventFragment;
    "PositionCreated(address,uint256,uint256)": EventFragment;
    "Redeem(address,uint256,uint256)": EventFragment;
    "RegularFeesPaid(uint256,uint256)": EventFragment;
    "Repay(address,uint256,uint256)": EventFragment;
    "RequestTransferPosition(address)": EventFragment;
    "RequestTransferPositionCanceled(address)": EventFragment;
    "RequestTransferPositionExecuted(address,address)": EventFragment;
    "RequestWithdrawal(address,uint256)": EventFragment;
    "RequestWithdrawalCanceled(address,uint256)": EventFragment;
    "RequestWithdrawalExecuted(address,uint256)": EventFragment;
    "SettleExpiredPosition(address,uint256,uint256)": EventFragment;
    "Withdrawal(address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ContractExpired"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Deposit"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "EmergencyShutdown"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "EndedSponsorPosition"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "FinalFeesPaid"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NewSponsor"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PositionCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Redeem"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RegularFeesPaid"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Repay"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RequestTransferPosition"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "RequestTransferPositionCanceled"
  ): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "RequestTransferPositionExecuted"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RequestWithdrawal"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RequestWithdrawalCanceled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RequestWithdrawalExecuted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SettleExpiredPosition"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Withdrawal"): EventFragment;
}

export class PricelessPositionManager extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: PricelessPositionManagerInterface;

  functions: {
    _getSyntheticDecimals(
      _collateralAddress: string,
      overrides?: CallOverrides
    ): Promise<[number] & { decimals: number }>;

    cancelTransferPosition(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    cancelWithdrawal(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    collateralCurrency(overrides?: CallOverrides): Promise<[string]>;

    contractState(overrides?: CallOverrides): Promise<[number]>;

    create(
      collateralAmount: { rawValue: BigNumberish },
      numTokens: { rawValue: BigNumberish },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    cumulativeFeeMultiplier(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { rawValue: BigNumber }>;

    deposit(
      collateralAmount: { rawValue: BigNumberish },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    depositTo(
      sponsor: string,
      collateralAmount: { rawValue: BigNumberish },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    emergencyShutdown(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    expirationTimestamp(overrides?: CallOverrides): Promise<[BigNumber]>;

    expire(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    expiryPrice(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { rawValue: BigNumber }>;

    financialProductLibrary(overrides?: CallOverrides): Promise<[string]>;

    finder(overrides?: CallOverrides): Promise<[string]>;

    getCollateral(
      sponsor: string,
      overrides?: CallOverrides
    ): Promise<[[BigNumber] & { rawValue: BigNumber }]>;

    getCurrentTime(overrides?: CallOverrides): Promise<[BigNumber]>;

    getOutstandingRegularFees(
      time: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        [BigNumber] & { rawValue: BigNumber },
        [BigNumber] & { rawValue: BigNumber },
        [BigNumber] & { rawValue: BigNumber }
      ] & {
        regularFee: [BigNumber] & { rawValue: BigNumber };
        latePenalty: [BigNumber] & { rawValue: BigNumber };
        totalPaid: [BigNumber] & { rawValue: BigNumber };
      }
    >;

    gulp(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    minSponsorTokens(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { rawValue: BigNumber }>;

    payRegularFees(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    pfc(
      overrides?: CallOverrides
    ): Promise<[[BigNumber] & { rawValue: BigNumber }]>;

    positions(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [
        [BigNumber] & { rawValue: BigNumber },
        BigNumber,
        [BigNumber] & { rawValue: BigNumber },
        [BigNumber] & { rawValue: BigNumber },
        BigNumber
      ] & {
        tokensOutstanding: [BigNumber] & { rawValue: BigNumber };
        withdrawalRequestPassTimestamp: BigNumber;
        withdrawalRequestAmount: [BigNumber] & { rawValue: BigNumber };
        rawCollateral: [BigNumber] & { rawValue: BigNumber };
        transferPositionRequestPassTimestamp: BigNumber;
      }
    >;

    priceIdentifier(overrides?: CallOverrides): Promise<[string]>;

    rawTotalPositionCollateral(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { rawValue: BigNumber }>;

    redeem(
      numTokens: { rawValue: BigNumberish },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    remargin(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    repay(
      numTokens: { rawValue: BigNumberish },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    requestTransferPosition(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    requestWithdrawal(
      collateralAmount: { rawValue: BigNumberish },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setCurrentTime(
      time: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    settleExpired(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    timerAddress(overrides?: CallOverrides): Promise<[string]>;

    tokenCurrency(overrides?: CallOverrides): Promise<[string]>;

    totalPositionCollateral(
      overrides?: CallOverrides
    ): Promise<[[BigNumber] & { rawValue: BigNumber }]>;

    totalTokensOutstanding(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { rawValue: BigNumber }>;

    transferPositionPassedRequest(
      newSponsorAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transformPrice(
      price: { rawValue: BigNumberish },
      requestTime: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[[BigNumber] & { rawValue: BigNumber }]>;

    transformPriceIdentifier(
      requestTime: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    withdraw(
      collateralAmount: { rawValue: BigNumberish },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    withdrawPassedRequest(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    withdrawalLiveness(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  _getSyntheticDecimals(
    _collateralAddress: string,
    overrides?: CallOverrides
  ): Promise<number>;

  cancelTransferPosition(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  cancelWithdrawal(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  collateralCurrency(overrides?: CallOverrides): Promise<string>;

  contractState(overrides?: CallOverrides): Promise<number>;

  create(
    collateralAmount: { rawValue: BigNumberish },
    numTokens: { rawValue: BigNumberish },
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  cumulativeFeeMultiplier(overrides?: CallOverrides): Promise<BigNumber>;

  deposit(
    collateralAmount: { rawValue: BigNumberish },
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  depositTo(
    sponsor: string,
    collateralAmount: { rawValue: BigNumberish },
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  emergencyShutdown(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  expirationTimestamp(overrides?: CallOverrides): Promise<BigNumber>;

  expire(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  expiryPrice(overrides?: CallOverrides): Promise<BigNumber>;

  financialProductLibrary(overrides?: CallOverrides): Promise<string>;

  finder(overrides?: CallOverrides): Promise<string>;

  getCollateral(
    sponsor: string,
    overrides?: CallOverrides
  ): Promise<[BigNumber] & { rawValue: BigNumber }>;

  getCurrentTime(overrides?: CallOverrides): Promise<BigNumber>;

  getOutstandingRegularFees(
    time: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [
      [BigNumber] & { rawValue: BigNumber },
      [BigNumber] & { rawValue: BigNumber },
      [BigNumber] & { rawValue: BigNumber }
    ] & {
      regularFee: [BigNumber] & { rawValue: BigNumber };
      latePenalty: [BigNumber] & { rawValue: BigNumber };
      totalPaid: [BigNumber] & { rawValue: BigNumber };
    }
  >;

  gulp(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  minSponsorTokens(overrides?: CallOverrides): Promise<BigNumber>;

  payRegularFees(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  pfc(
    overrides?: CallOverrides
  ): Promise<[BigNumber] & { rawValue: BigNumber }>;

  positions(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<
    [
      [BigNumber] & { rawValue: BigNumber },
      BigNumber,
      [BigNumber] & { rawValue: BigNumber },
      [BigNumber] & { rawValue: BigNumber },
      BigNumber
    ] & {
      tokensOutstanding: [BigNumber] & { rawValue: BigNumber };
      withdrawalRequestPassTimestamp: BigNumber;
      withdrawalRequestAmount: [BigNumber] & { rawValue: BigNumber };
      rawCollateral: [BigNumber] & { rawValue: BigNumber };
      transferPositionRequestPassTimestamp: BigNumber;
    }
  >;

  priceIdentifier(overrides?: CallOverrides): Promise<string>;

  rawTotalPositionCollateral(overrides?: CallOverrides): Promise<BigNumber>;

  redeem(
    numTokens: { rawValue: BigNumberish },
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  remargin(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  repay(
    numTokens: { rawValue: BigNumberish },
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  requestTransferPosition(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  requestWithdrawal(
    collateralAmount: { rawValue: BigNumberish },
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setCurrentTime(
    time: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  settleExpired(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  timerAddress(overrides?: CallOverrides): Promise<string>;

  tokenCurrency(overrides?: CallOverrides): Promise<string>;

  totalPositionCollateral(
    overrides?: CallOverrides
  ): Promise<[BigNumber] & { rawValue: BigNumber }>;

  totalTokensOutstanding(overrides?: CallOverrides): Promise<BigNumber>;

  transferPositionPassedRequest(
    newSponsorAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transformPrice(
    price: { rawValue: BigNumberish },
    requestTime: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[BigNumber] & { rawValue: BigNumber }>;

  transformPriceIdentifier(
    requestTime: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  withdraw(
    collateralAmount: { rawValue: BigNumberish },
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  withdrawPassedRequest(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  withdrawalLiveness(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    _getSyntheticDecimals(
      _collateralAddress: string,
      overrides?: CallOverrides
    ): Promise<number>;

    cancelTransferPosition(overrides?: CallOverrides): Promise<void>;

    cancelWithdrawal(overrides?: CallOverrides): Promise<void>;

    collateralCurrency(overrides?: CallOverrides): Promise<string>;

    contractState(overrides?: CallOverrides): Promise<number>;

    create(
      collateralAmount: { rawValue: BigNumberish },
      numTokens: { rawValue: BigNumberish },
      overrides?: CallOverrides
    ): Promise<void>;

    cumulativeFeeMultiplier(overrides?: CallOverrides): Promise<BigNumber>;

    deposit(
      collateralAmount: { rawValue: BigNumberish },
      overrides?: CallOverrides
    ): Promise<void>;

    depositTo(
      sponsor: string,
      collateralAmount: { rawValue: BigNumberish },
      overrides?: CallOverrides
    ): Promise<void>;

    emergencyShutdown(overrides?: CallOverrides): Promise<void>;

    expirationTimestamp(overrides?: CallOverrides): Promise<BigNumber>;

    expire(overrides?: CallOverrides): Promise<void>;

    expiryPrice(overrides?: CallOverrides): Promise<BigNumber>;

    financialProductLibrary(overrides?: CallOverrides): Promise<string>;

    finder(overrides?: CallOverrides): Promise<string>;

    getCollateral(
      sponsor: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { rawValue: BigNumber }>;

    getCurrentTime(overrides?: CallOverrides): Promise<BigNumber>;

    getOutstandingRegularFees(
      time: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        [BigNumber] & { rawValue: BigNumber },
        [BigNumber] & { rawValue: BigNumber },
        [BigNumber] & { rawValue: BigNumber }
      ] & {
        regularFee: [BigNumber] & { rawValue: BigNumber };
        latePenalty: [BigNumber] & { rawValue: BigNumber };
        totalPaid: [BigNumber] & { rawValue: BigNumber };
      }
    >;

    gulp(overrides?: CallOverrides): Promise<void>;

    minSponsorTokens(overrides?: CallOverrides): Promise<BigNumber>;

    payRegularFees(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { rawValue: BigNumber }>;

    pfc(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { rawValue: BigNumber }>;

    positions(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [
        [BigNumber] & { rawValue: BigNumber },
        BigNumber,
        [BigNumber] & { rawValue: BigNumber },
        [BigNumber] & { rawValue: BigNumber },
        BigNumber
      ] & {
        tokensOutstanding: [BigNumber] & { rawValue: BigNumber };
        withdrawalRequestPassTimestamp: BigNumber;
        withdrawalRequestAmount: [BigNumber] & { rawValue: BigNumber };
        rawCollateral: [BigNumber] & { rawValue: BigNumber };
        transferPositionRequestPassTimestamp: BigNumber;
      }
    >;

    priceIdentifier(overrides?: CallOverrides): Promise<string>;

    rawTotalPositionCollateral(overrides?: CallOverrides): Promise<BigNumber>;

    redeem(
      numTokens: { rawValue: BigNumberish },
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { rawValue: BigNumber }>;

    remargin(overrides?: CallOverrides): Promise<void>;

    repay(
      numTokens: { rawValue: BigNumberish },
      overrides?: CallOverrides
    ): Promise<void>;

    requestTransferPosition(overrides?: CallOverrides): Promise<void>;

    requestWithdrawal(
      collateralAmount: { rawValue: BigNumberish },
      overrides?: CallOverrides
    ): Promise<void>;

    setCurrentTime(
      time: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    settleExpired(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { rawValue: BigNumber }>;

    timerAddress(overrides?: CallOverrides): Promise<string>;

    tokenCurrency(overrides?: CallOverrides): Promise<string>;

    totalPositionCollateral(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { rawValue: BigNumber }>;

    totalTokensOutstanding(overrides?: CallOverrides): Promise<BigNumber>;

    transferPositionPassedRequest(
      newSponsorAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    transformPrice(
      price: { rawValue: BigNumberish },
      requestTime: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { rawValue: BigNumber }>;

    transformPriceIdentifier(
      requestTime: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    withdraw(
      collateralAmount: { rawValue: BigNumberish },
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { rawValue: BigNumber }>;

    withdrawPassedRequest(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { rawValue: BigNumber }>;

    withdrawalLiveness(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {
    ContractExpired(
      caller?: string | null
    ): TypedEventFilter<[string], { caller: string }>;

    Deposit(
      sponsor?: string | null,
      collateralAmount?: BigNumberish | null
    ): TypedEventFilter<
      [string, BigNumber],
      { sponsor: string; collateralAmount: BigNumber }
    >;

    EmergencyShutdown(
      caller?: string | null,
      originalExpirationTimestamp?: null,
      shutdownTimestamp?: null
    ): TypedEventFilter<
      [string, BigNumber, BigNumber],
      {
        caller: string;
        originalExpirationTimestamp: BigNumber;
        shutdownTimestamp: BigNumber;
      }
    >;

    EndedSponsorPosition(
      sponsor?: string | null
    ): TypedEventFilter<[string], { sponsor: string }>;

    FinalFeesPaid(
      amount?: BigNumberish | null
    ): TypedEventFilter<[BigNumber], { amount: BigNumber }>;

    NewSponsor(
      sponsor?: string | null
    ): TypedEventFilter<[string], { sponsor: string }>;

    PositionCreated(
      sponsor?: string | null,
      collateralAmount?: BigNumberish | null,
      tokenAmount?: BigNumberish | null
    ): TypedEventFilter<
      [string, BigNumber, BigNumber],
      { sponsor: string; collateralAmount: BigNumber; tokenAmount: BigNumber }
    >;

    Redeem(
      sponsor?: string | null,
      collateralAmount?: BigNumberish | null,
      tokenAmount?: BigNumberish | null
    ): TypedEventFilter<
      [string, BigNumber, BigNumber],
      { sponsor: string; collateralAmount: BigNumber; tokenAmount: BigNumber }
    >;

    RegularFeesPaid(
      regularFee?: BigNumberish | null,
      lateFee?: BigNumberish | null
    ): TypedEventFilter<
      [BigNumber, BigNumber],
      { regularFee: BigNumber; lateFee: BigNumber }
    >;

    Repay(
      sponsor?: string | null,
      numTokensRepaid?: BigNumberish | null,
      newTokenCount?: BigNumberish | null
    ): TypedEventFilter<
      [string, BigNumber, BigNumber],
      { sponsor: string; numTokensRepaid: BigNumber; newTokenCount: BigNumber }
    >;

    RequestTransferPosition(
      oldSponsor?: string | null
    ): TypedEventFilter<[string], { oldSponsor: string }>;

    RequestTransferPositionCanceled(
      oldSponsor?: string | null
    ): TypedEventFilter<[string], { oldSponsor: string }>;

    RequestTransferPositionExecuted(
      oldSponsor?: string | null,
      newSponsor?: string | null
    ): TypedEventFilter<
      [string, string],
      { oldSponsor: string; newSponsor: string }
    >;

    RequestWithdrawal(
      sponsor?: string | null,
      collateralAmount?: BigNumberish | null
    ): TypedEventFilter<
      [string, BigNumber],
      { sponsor: string; collateralAmount: BigNumber }
    >;

    RequestWithdrawalCanceled(
      sponsor?: string | null,
      collateralAmount?: BigNumberish | null
    ): TypedEventFilter<
      [string, BigNumber],
      { sponsor: string; collateralAmount: BigNumber }
    >;

    RequestWithdrawalExecuted(
      sponsor?: string | null,
      collateralAmount?: BigNumberish | null
    ): TypedEventFilter<
      [string, BigNumber],
      { sponsor: string; collateralAmount: BigNumber }
    >;

    SettleExpiredPosition(
      caller?: string | null,
      collateralReturned?: BigNumberish | null,
      tokensBurned?: BigNumberish | null
    ): TypedEventFilter<
      [string, BigNumber, BigNumber],
      { caller: string; collateralReturned: BigNumber; tokensBurned: BigNumber }
    >;

    Withdrawal(
      sponsor?: string | null,
      collateralAmount?: BigNumberish | null
    ): TypedEventFilter<
      [string, BigNumber],
      { sponsor: string; collateralAmount: BigNumber }
    >;
  };

  estimateGas: {
    _getSyntheticDecimals(
      _collateralAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    cancelTransferPosition(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    cancelWithdrawal(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    collateralCurrency(overrides?: CallOverrides): Promise<BigNumber>;

    contractState(overrides?: CallOverrides): Promise<BigNumber>;

    create(
      collateralAmount: { rawValue: BigNumberish },
      numTokens: { rawValue: BigNumberish },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    cumulativeFeeMultiplier(overrides?: CallOverrides): Promise<BigNumber>;

    deposit(
      collateralAmount: { rawValue: BigNumberish },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    depositTo(
      sponsor: string,
      collateralAmount: { rawValue: BigNumberish },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    emergencyShutdown(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    expirationTimestamp(overrides?: CallOverrides): Promise<BigNumber>;

    expire(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    expiryPrice(overrides?: CallOverrides): Promise<BigNumber>;

    financialProductLibrary(overrides?: CallOverrides): Promise<BigNumber>;

    finder(overrides?: CallOverrides): Promise<BigNumber>;

    getCollateral(
      sponsor: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getCurrentTime(overrides?: CallOverrides): Promise<BigNumber>;

    getOutstandingRegularFees(
      time: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    gulp(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    minSponsorTokens(overrides?: CallOverrides): Promise<BigNumber>;

    payRegularFees(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    pfc(overrides?: CallOverrides): Promise<BigNumber>;

    positions(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    priceIdentifier(overrides?: CallOverrides): Promise<BigNumber>;

    rawTotalPositionCollateral(overrides?: CallOverrides): Promise<BigNumber>;

    redeem(
      numTokens: { rawValue: BigNumberish },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    remargin(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    repay(
      numTokens: { rawValue: BigNumberish },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    requestTransferPosition(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    requestWithdrawal(
      collateralAmount: { rawValue: BigNumberish },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setCurrentTime(
      time: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    settleExpired(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    timerAddress(overrides?: CallOverrides): Promise<BigNumber>;

    tokenCurrency(overrides?: CallOverrides): Promise<BigNumber>;

    totalPositionCollateral(overrides?: CallOverrides): Promise<BigNumber>;

    totalTokensOutstanding(overrides?: CallOverrides): Promise<BigNumber>;

    transferPositionPassedRequest(
      newSponsorAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transformPrice(
      price: { rawValue: BigNumberish },
      requestTime: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    transformPriceIdentifier(
      requestTime: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    withdraw(
      collateralAmount: { rawValue: BigNumberish },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    withdrawPassedRequest(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    withdrawalLiveness(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    _getSyntheticDecimals(
      _collateralAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    cancelTransferPosition(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    cancelWithdrawal(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    collateralCurrency(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    contractState(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    create(
      collateralAmount: { rawValue: BigNumberish },
      numTokens: { rawValue: BigNumberish },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    cumulativeFeeMultiplier(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    deposit(
      collateralAmount: { rawValue: BigNumberish },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    depositTo(
      sponsor: string,
      collateralAmount: { rawValue: BigNumberish },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    emergencyShutdown(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    expirationTimestamp(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    expire(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    expiryPrice(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    financialProductLibrary(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    finder(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getCollateral(
      sponsor: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getCurrentTime(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getOutstandingRegularFees(
      time: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    gulp(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    minSponsorTokens(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    payRegularFees(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    pfc(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    positions(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    priceIdentifier(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    rawTotalPositionCollateral(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    redeem(
      numTokens: { rawValue: BigNumberish },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    remargin(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    repay(
      numTokens: { rawValue: BigNumberish },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    requestTransferPosition(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    requestWithdrawal(
      collateralAmount: { rawValue: BigNumberish },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setCurrentTime(
      time: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    settleExpired(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    timerAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    tokenCurrency(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    totalPositionCollateral(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    totalTokensOutstanding(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    transferPositionPassedRequest(
      newSponsorAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transformPrice(
      price: { rawValue: BigNumberish },
      requestTime: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    transformPriceIdentifier(
      requestTime: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    withdraw(
      collateralAmount: { rawValue: BigNumberish },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    withdrawPassedRequest(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    withdrawalLiveness(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
