/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  AdministrateeInterface,
  AdministrateeInterfaceInterface,
} from "../AdministrateeInterface";

const _abi = [
  {
    inputs: [],
    name: "emergencyShutdown",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "pfc",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "rawValue",
            type: "uint256",
          },
        ],
        internalType: "struct FixedPoint.Unsigned",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "remargin",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class AdministrateeInterface__factory {
  static readonly abi = _abi;
  static createInterface(): AdministrateeInterfaceInterface {
    return new utils.Interface(_abi) as AdministrateeInterfaceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): AdministrateeInterface {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as AdministrateeInterface;
  }
}
