/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  ExpiringContractInterface,
  ExpiringContractInterfaceInterface,
} from "../ExpiringContractInterface";

const _abi = [
  {
    inputs: [],
    name: "expirationTimestamp",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class ExpiringContractInterface__factory {
  static readonly abi = _abi;
  static createInterface(): ExpiringContractInterfaceInterface {
    return new utils.Interface(_abi) as ExpiringContractInterfaceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ExpiringContractInterface {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ExpiringContractInterface;
  }
}
