/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  FinancialProductLibrary,
  FinancialProductLibraryInterface,
} from "../FinancialProductLibrary";

const _abi = [
  {
    inputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "rawValue",
            type: "uint256",
          },
        ],
        internalType: "struct FixedPoint.Unsigned",
        name: "oraclePrice",
        type: "tuple",
      },
      {
        components: [
          {
            internalType: "uint256",
            name: "rawValue",
            type: "uint256",
          },
        ],
        internalType: "struct FixedPoint.Unsigned",
        name: "collateralRequirement",
        type: "tuple",
      },
    ],
    name: "transformCollateralRequirement",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "rawValue",
            type: "uint256",
          },
        ],
        internalType: "struct FixedPoint.Unsigned",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "rawValue",
            type: "uint256",
          },
        ],
        internalType: "struct FixedPoint.Unsigned",
        name: "oraclePrice",
        type: "tuple",
      },
      {
        internalType: "uint256",
        name: "requestTime",
        type: "uint256",
      },
    ],
    name: "transformPrice",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "rawValue",
            type: "uint256",
          },
        ],
        internalType: "struct FixedPoint.Unsigned",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "priceIdentifier",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "requestTime",
        type: "uint256",
      },
    ],
    name: "transformPriceIdentifier",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class FinancialProductLibrary__factory {
  static readonly abi = _abi;
  static createInterface(): FinancialProductLibraryInterface {
    return new utils.Interface(_abi) as FinancialProductLibraryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): FinancialProductLibrary {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as FinancialProductLibrary;
  }
}
