/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  LongShortPairFinancialProductLibrary,
  LongShortPairFinancialProductLibraryInterface,
} from "../LongShortPairFinancialProductLibrary";

const _abi = [
  {
    inputs: [
      {
        internalType: "int256",
        name: "expiryPrice",
        type: "int256",
      },
    ],
    name: "percentageLongCollateralAtExpiry",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class LongShortPairFinancialProductLibrary__factory {
  static readonly abi = _abi;
  static createInterface(): LongShortPairFinancialProductLibraryInterface {
    return new utils.Interface(
      _abi
    ) as LongShortPairFinancialProductLibraryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): LongShortPairFinancialProductLibrary {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as LongShortPairFinancialProductLibrary;
  }
}
